# Generated by Django 5.2.6 on 2025-09-15 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('realizado', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbearia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbearia')),
            ],
        ),
    ]
