# Generated by Django 5.2.6 on 2025-09-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0002_agendamento_data_criacao_agendamento_nome_avulso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='barbeiro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome_avulso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
